name: Deploy Data Notebooks

on:
  push:
    branches:
      - prod
      - test
    paths:
      - 'experimental/SMUS-CICD-pipeline-cli/examples/analytic-workflow/data-notebooks/**'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/smus-multi-env-reusable.yml
    with:
      manifest_path: 'experimental/SMUS-CICD-pipeline-cli/examples/analytic-workflow/data-notebooks/manifest.yaml'
      test_target: 'test'
      prod_target: 'prod'
      deploy_to_prod: ${{ github.ref == 'refs/heads/prod' }}
