name: Deploy GenAI

on:
  push:
    branches:
      - main
      - test
      - amirb_feature_branch
    paths:
      - 'experimental/SMUS-CICD-pipeline-cli/examples/analytic-workflow/genai/**'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/smus-direct-deploy.yml
    with:
      manifest_path: 'experimental/SMUS-CICD-pipeline-cli/examples/analytic-workflow/genai/manifest.yaml'
      test_target: 'test'
      prod_target: 'prod'
      deploy_to_prod: ${{ github.ref == 'refs/heads/main' }}
