name: Deploy Data Notebooks

on:
  push:
    branches:
      - amirbo_feature_branch
      # - main
      - test
      - amirb_feature_branch
    paths:
      - 'experimental/SMUS-CICD-pipeline-cli/examples/analytic-workflow/data-notebooks/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/smus-direct-deploy.yml
    with:
      manifest_path: 'experimental/SMUS-CICD-pipeline-cli/examples/analytic-workflow/data-notebooks/manifest.yaml'
      test_target: 'test'
