name: Deploy ML Training

on:
  push:
    branches:
      - prod
      - test
    paths:
      - 'experimental/SMUS-CICD-pipeline-cli/examples/analytic-workflow/ml/training/**'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./experimental/SMUS-CICD-pipeline-cli/git-templates/smus-multi-env-reusable.yml
    with:
      manifest_path: 'experimental/SMUS-CICD-pipeline-cli/examples/analytic-workflow/ml/training/manifest.yaml'
      test_target: 'test'
      prod_target: 'prod'
      deploy_to_prod: ${{ github.ref == 'refs/heads/prod' }}
